import = ["~/.config/alacritty/keybinds.toml",
"~/.config/alacritty/colors.toml",]

live_config_reload = true

[scrolling]
multiplier = 10

[keyboard]
bindings = [
{ key= "Left", mods= "Alt", chars= "\u001BB" }, # Skip word left
{ key= "Right", mods= "Alt", chars= "\u001BF" }, # Skip word right
{ key= "Left", mods= "Command", chars= "\u001bOH"}, # Go to Beginning
{ key= "Right", mods= "Command", chars= "\u001bOF"}, # Go to End
]

[window]
# decorations = "buttonless"
dynamic_padding =false
opacity = 0.8
blur = true
decorations_theme_variant = "Dark"
startup_mode = "Maximized"
# This makes option work as alt. You need this for things
# like tmux when you want to use the META key on Mac OS.
# https://alacritty.org/config-alacritty.html#s20
option_as_alt = "OnlyLeft"

[window.padding]
x = 0 
y = 0

[font]
# I have my font size at 23 because it is a prime number.
# Neovim sets my scrolloff to have my cursor in the middle of the screen, so if
# I have a prime number, I should be able to avoid off by 1 errors with the
# centering of my cursor.
size = 23.0
# I use DejaVu Sans Mono because it supports characters like ₕ
# If you want to try to find another font, go here: https://unicode.scarfboy.com/
# Then, enter a character that doesn't usually show up in other fonts.
#normal = { family = "DejaVu Sans Mono" }
#normal = { family = "BlexMono Nerd Font Mono Light" }
normal = { family = "Jetbrains Mono" }
#normal = { family = "0xProto Font Mono Light" }

